name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        id: gradle
        with:
          arguments: build
